leftnav:
- identifier: b91650b6-c23e-65c3-d3d2-1d080801c811
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: f8c0d4e0-c157-0358-2762-3e7b50631c7f
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a475a835-2b88-c8a9-eb80-ed3d5213bdd4
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 22c87243-e00c-38f9-135a-54434bb5ca86
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 0245c9eb-9868-8276-516b-fdf64623a690
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: b32adfc9-5c85-9ce1-d213-f2a525554084
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: 0439ec05-fe37-6e9e-7a8d-6c6d53e5c840
  name: Projects
  pageRef: /pages/projects
  weight: 70
